__include__: [
  '../dataset/coco_dark_noise_segm.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd.yml',
]


output_dir: ./output/debug_rtdetrv2_r18vd_segm


PResNet:
  depth: 18
  freeze_at: -1
  freeze_norm: False
  pretrained: True


MaskHybridEncoder:
  in_channels: [64, 128, 256, 512]
  hidden_dim: 256
  expansion: 0.5


MaskRTDETRTransformer:
  num_layers: 3


epoches: 120 

# optimizer:
#   type: AdamW
#   params:
#     - 
#       params: '^(?=.*(?:norm|bn)).*$'
#       weight_decay: 0.

optimizer:
  type: SGD
  params:
    - 
      params: '^(?=.*(?:norm|bn)).*$' # (idk what its for but yeah) refer to yaml_config.py#L107
      weight_decay: 0.


train_dataloader: 
  dataset: 
    transforms:
      policy:
        epoch: 50
  collate_fn:
    scales: ~
